### ISSUE TITLE
02 pcie ddr4  error

### ISSUE THREAD

**Issue by whyaysd** [maswx/vu13p#5]
Phase 1 Generate And Synthesize MIG Cores
ERROR: [Mig 66-99] Memory Core Error - [base_i/ddr4_3] Either port(s) c0_sys_clk_p, c0_sys_clk_n is/are not placed or un-supported clocking structure/circuit for memory ip instance. Please refer to clocking section of PG150 for supported clocking structures. 
ERROR: [Mig 66-99] Memory Core Error - [base_i/ddr4_3] Port(s) c3_ddr4_clk_clk_n,c3_ddr4_clk_clk_p is/are not placed. Assign all ports to valid sites. 
ERROR: [Mig 66-99] Memory Core Error - [base_i/ddr4_2] Either port(s) c0_sys_clk_p, c0_sys_clk_n is/are not placed or un-supported clocking structure/circuit for memory ip instance. Please refer to clocking section of PG150 for supported clocking structures. 
ERROR: [Mig 66-99] Memory Core Error - [base_i/ddr4_2] Port(s) c2_ddr4_clk_clk_n,c2_ddr4_clk_clk_p is/are not placed. Assign all ports to valid sites. 
ERROR: [Mig 66-99] Memory Core Error - [base_i/ddr4_1] Either port(s) c0_sys_clk_p, c0_sys_clk_n is/are not placed or un-supported clocking structure/circuit for memory ip instance. Please refer to clocking section of PG150 for supported clocking structures. 
ERROR: [Mig 66-99] Memory Core Error - [base_i/ddr4_1] Port(s) c1_ddr4_clk_clk_n,c1_ddr4_clk_clk_p is/are not placed. Assign all ports to valid sites. 
ERROR: [Mig 66-99] Memory Core Error - [base_i/ddr4_0] Either port(s) c0_sys_clk_p, c0_sys_clk_n is/are not placed or un-supported clocking structure/circuit for memory ip instance. Please refer to clocking section of PG150 for supported clocking structures.

**Comment by maswx** [comment]
中间有一次改了xdc中ddr的文件约束名。改回旧版本就好了。

新版本
```
  1 set_property -dict {LOC G25  IOSTANDARD DIFF_SSTL12    } [get_ports c0_ddr4_clk_p]
  2 set_property -dict {LOC G24  IOSTANDARD DIFF_SSTL12    } [get_ports c0_ddr4_clk_n]
```
旧版本
```
  1 set_property -dict {LOC G25  IOSTANDARD DIFF_SSTL12    } [get_ports c0_ddr4_clk_clk_p]
  2 set_property -dict {LOC G24  IOSTANDARD DIFF_SSTL12    } [get_ports c0_ddr4_clk_clk_n]
```
4组DDR都改。等我有空再把02中的这个问题修复。

**Comment by whyaysd** [comment]
我看报错写的是c0_sys_clk_p，是不是应该改成这个名子
