### ISSUE TITLE
Tandem stage 1 I/O cell 'pcie_perst_IBUF_inst/INBUF_INST' does not belong to a pblock.

### ISSUE THREAD

**Issue by whyaysd** [maswx/vu13p#6]
NFO: [IP_Flow 19-1839] IP Catalog is up to date.
INFO: [DRC 23-27] Running DRC with 8 threads
INFO: [Vivado_Tcl 2-168] The results of DRC are in file /home/xsr/Desktop/VU13P/vu13p/prj/02_pcie_ddr4x4/project/project.runs/impl_1/base_wrapper_drc_opted.rpt.
report_drc completed successfully
report_drc: Time (s): cpu = 00:00:38 ; elapsed = 00:00:09 . Memory (MB): peak = 9014.684 ; gain = 12.020 ; free physical = 77457 ; free virtual = 99952
INFO: [Chipscope 16-240] Debug cores have already been implemented
Command: place_design
Attempting to get a license for feature 'Implementation' and/or device 'xcvu13p'
INFO: [Common 17-349] Got license for feature 'Implementation' and/or device 'xcvu13p'
INFO: [Common 17-83] Releasing license: Implementation
226 Infos, 151 Warnings, 14 Critical Warnings and 1 Errors encountered.
place_design failed
ERROR: [Constraints 18-4604] Tandem stage 1 I/O cell 'pcie_perst_IBUF_inst/INBUF_INST' does not belong to a pblock. Stage 1 I/O cells should be added to stage1 I/O pblock. Please identify stage 1 I/O pblock by setting property 'HD.TANDEM_IP_PBLOCK' to 'Stage1_IO', Vivado will automatically assign stage 1 I/O cells to this pblock. Alternatively, you can explicitly assign pblock membership for this cell by using 'add_cells_to_pblock' command.
INFO: [Common 17-206] Exiting Vivado at Sat Nov 18 18:05:41 2023...
[Sat Nov 18 18:05:42 2023] impl_1 finished
WARNING: [Vivado 12-13638] Failed runs(s) : 'impl_1'

**Comment by maswx** [comment]
啊，忘了关TandemPCIe了，这是个没卵用的功能。简单的处理办法是双击xdma模块，关掉TandemPCIe

**Comment by maswx** [comment]
今天晚些时候将修复这两bug

**Comment by maswx** [comment]
工程已更新，
1. 移除了TandemPCIe 
2. 简化了原理框图设计，但是综合起来好像变慢了，应该是和时钟约束有关系。
3. 增加了c驱动。
4. git pull 拉取最新代码, do this: 
```shell
step1. cd vu13p/prj/02_pcie_ddr4x4 #到达工程路径
step2. `make` #编译
step3. #王者峡谷开一局。预计编译时间1个小时
```

TODO：
后续会增加上位机xdma中断的example

**Comment by maswx** [comment]
![image](https://github.com/maswx/vu13p/assets/19650790/98b00c07-269f-4e0d-a778-a77992217a6d)

我这边验证通过了，问题已关闭

**Comment by maswx** [comment]
![5db889379835c1d29ce6361811abd36b](https://github.com/maswx/vu13p/assets/19650790/93cc9cea-a928-4a38-92b1-9b9fd392bdb5)

**Comment by whyaysd** [comment]
大佬，请教一下，我用之前的版本测试的时候，写入带宽只有2GB/s 更新到现在这个版本以后，速度快了很多，大佬是有优化速度吗

**Comment by maswx** [comment]
改了下架构。之前的架构不太好。
另外在这次的架构里对全部总线做了异步处理。
